### ISSUE TITLE
Documentation error...

### ISSUE THREAD

**Issue by skoontastic** [grantholle/powerschool-api#1]
Looks like there is a tiny error in the documentation. The provider needs to a capital "S" in PowerschoolServiceProvider:

php artisan vendor:publish --provider=GrantHolle\PowerSchool\PowerschoolServiceProvider

Should be:

php artisan vendor:publish --provider=GrantHolle\PowerSchool\PowerSchoolServiceProvider

**Comment by grantholle** [comment]
Thanks for spotting that
