### ISSUE TITLE
Response error on pagination...

### ISSUE THREAD

**Issue by skoontastic** [grantholle/powerschool-api#14]
Hey Grant, hope you are doing well! I'm running into an error getting data back from any of my PowerQueries. If I just run a `post()` to the PQ it returns the data as expected. If I run a `paginate()` on it, I get the correct data back but then I get a TypeError:

```
$request = PowerSchool::pq('app.schoolwire.teachers');

while ($records = $request->paginate(100)){
	foreach($records as $r) {
	 echo 'Id ' . $r['id'] . "\n";
	};
};
```
Result:
```
...
Id id_99650
Id id_93480
Id id_54325
Id id_54322
Id id_54320

TypeError: GrantHolle\PowerSchool\Api\Response::inferData(): Argument #1 ($data) must be of type array, string given, called in /Users/jeremyschoonover/Sites/php/schoolcore-svelte/vendor/grantholle/powerschool-api/src/Response.php on line 49
```
I'm using TinkerWell to run the code and monitoring the results in Ray. The odd thing is that Ray doesn't seem to register the error.

If I run the PQ in with a raw HTTP request I get what looks like the correct JSON back. Any thoughts?

**Comment by grantholle** [comment]
Hey! I've published version `3.2.3` to catch this string thing, and am curious if it fixes the problem. Update the package and let me know!

If it doesn't, do you mind sending the structure of what gets returned? Feel free to redact any data. I'm just curious about the actual structure of the responses PS returns

**Comment by grantholle** [comment]
When it gets to the point of `Undefined array key "id"`, could you do a `ray($r)` and see what the output is?

```php
$request = PowerSchool::pq('app.schoolwire.teachers');

while ($records = $request->paginate(100)){
    foreach($records as $r) {
        if (!isset($r['id']) {
            ray($r);
            continue;
        }

        echo 'Id ' . $r['id'] . "\n";
    }
}
```

**Comment by skoontastic** [comment]
So `rd()` actually ends the loop and everything works as expected. `dd()` gives me this:

```
...
Id id_99650
Id id_93480
Id id_54325
Id id_54322
Id id_54320
array:1 [
  "name" => "users"
]
```

**Comment by grantholle** [comment]
Thanks for that debugging. I found the issue and in version `3.2.4` I'm hoping that it's fixed. I added a test case for your specific response.

It theoretically should now paginate and iterate through the results as expected, with the bonus of not going on forever and ever...

**Comment by skoontastic** [comment]
Boom, works! Thanks!

**Comment by grantholle** [comment]
Niiiiiice! Thanks for helping figure out the problem!
