### ISSUE TITLE
Insert/Get Parent information

### ISSUE THREAD

**Issue by vikramsra** [grantholle/powerschool-api#15]
Hi,

First of all thank you for the wonderful extension. I would like to know about a way to Get student guardian details and how we can insert the same.

Thanks in advance

**Comment by grantholle** [comment]
Do you have access to the [resources documentation](https://support.powerschool.com/developer/#/page/core-resources)?

There is an endpoint for getting a student contacts - get `/ws/contacts/student/{dcid}`. 
Creating contacts has an endpoint at post `/ws/contacts/contact`.

All of the details are on that documentation page. You'll need to filter by plugin.

**Comment by vikramsra** [comment]
Yes, I think I am getting the hang of it. Let me quickly try this

**Comment by vikramsra** [comment]
```
$requestData = [
                'firstName' => 'ParentFN',
                'lastName' => 'ParentLN',
                'active' => true,
        ];        
            $request =  PowerSchool::endpoint('/ws/contacts/contact')
            ->with($requestData)->post();
```
Is this the correct way?

**Comment by grantholle** [comment]
Yes that looks correct to me. Looking at the documentation, the data might be nested under `contact`, like this:

```php
$requestData = [
    'contact' => [
        'firstName' => 'ParentFN',
        'lastName' => 'ParentLN',
        'active' => true,
    ],
];
```

If you try that, you should be able to see that it works or what errors it gives. I've actually not tried this endpoint before. But the rest of your snippet looks right to me.

**Comment by vikramsra** [comment]
It throws an error bad request. Unrecognized field.

**Comment by grantholle** [comment]
Ok, it might not need the `contact` nesting. I guess try how you originally had it.

**Comment by vikramsra** [comment]
That hit with an error
ws/contacts/contact` resulted in a `500 Internal Server Error` response

**Comment by vikramsra** [comment]
Resolved. Issue was I was passing it in param and not in body. Thanks again for such a wonderful extension.

**Comment by grantholle** [comment]
Awesome, glad to hear!
