### ISSUE TITLE
asJsonResponse() throw an exception

### ISSUE THREAD

**Issue by Hujairi** [grantholle/powerschool-api#17]
GrantHolle\PowerSchool\Api\Response::__construct(): Argument #1 ($data) must be of type array, Illuminate\Http\JsonResponse given, called in /Users/mahmoodhujairi/Development/PStest/vendor/grantholle/powerschool-api/src/RequestBuilder.php on line 737

Response class constructor only accepts an array, therefor if I use asJsonResponse() it throw the above error

**Comment by grantholle** [comment]
This is fixed in `4.2.0`. Let me know if you have issues
