### ISSUE TITLE
Syncing students, teachers, and courses...

### ISSUE THREAD

**Issue by skoontastic** [grantholle/powerschool-api#2]
Hi Grant,

This isn't an issue, but I stumbled on your project because I am toying around with building a school-to-home communication tool using Laravel for my school district. Basically, I want parents to be able to log in to this and see all of their student classes and calendars in one spot. They will also be able to interact with their teachers, and vice versa.

We use PowerSchool and my goal was to sync the student, teacher, guardian, and course info into the system nightly, creating user accounts and associating them with their classes. I started digging into the PowerSchool API, but then discovered this project. Do you think I could accomplish my goal of syncing that information using this?

Thanks for your work on this, and for any help you can give!

**Comment by grantholle** [comment]
Hey! Thanks for reaching out.

All of that is certainly possible using this package, but you'll also have to pair it with a PowerSchool plugin that contains the queries you need to pull that information. It's just a matter of understanding the database structure to perform the queries you need. Unfortunately their schema is, in a word, awful. I don't know how much exposure you have to creating plugins or interacting with their database, but the learning curve is steep.

If you have access to the ["developer"](https://support.powerschool.com/developer) resources, but it will begin to give you some exposure of some of the things that come out of the box. This package will make it much easier to actually perform the requests, but there is a lot of leg room prior to making that first request... I have worked with PowerSchool and built many plugins for over 3 years now and feel like I have a solid understanding of what it takes. It's one of those "abandon all hope ye who enter here" situations. Feel free to [email](mailto:hollegrant@gmail.com) me directly. I love to bash PowerSchool whenever I get the chance.

**Comment by skoontastic** [comment]
Ha, nice! Their db structure is terrible. I was able to get a plugin installed and can make http requests with the built-in Zttp/Guzzle feature in Laravel 7. I think that's mostly what I'll need, but I'll be sure to hit you up if I run into anything bizarre, which is most likely to happen. Thanks for getting back to me.
